server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true

info:
  app.name: aking-springcloud
  company.name: aking.com

zuul:
  routes:
    mydept.serviceId: spring-cloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: spring-cloud-provider-dept #不能再通过服务名访问
